apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: chicago-taxi-dataset-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.10, pipelines.kubeflow.org/pipeline_compilation_time: '2021-12-17T16:49:57.073009',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "Chicago-taxi-dataset"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.10}
spec:
  entrypoint: chicago-taxi-dataset
  templates:
  - name: ann-test
    container:
      args: []
      command: [python, index.py, --model, /tmp/inputs/Model/data, --x-test, /tmp/inputs/X_Test/data,
        --y-test, /tmp/inputs/Y_Test/data]
      image: gcr.io/niveustraining/taxi-dataset/neural-network/test:latest
    inputs:
      artifacts:
      - {name: ann-train-Model, path: /tmp/inputs/Model/data}
      - {name: preprocess-Y-Test, path: /tmp/inputs/X_Test/data}
      - {name: feature-scale-X-Test-Feature-Scaled, path: /tmp/inputs/Y_Test/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.10
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"command": ["python", "index.py", "--model", {"inputPath": "Model"}, "--x-test",
          {"inputPath": "X Test"}, "--y-test", {"inputPath": "Y Test"}], "image":
          "gcr.io/niveustraining/taxi-dataset/neural-network/test:latest"}}, "inputs":
          [{"name": "Model", "type": "LocalPath"}, {"name": "X Test", "type": "LocalPath"},
          {"name": "Y Test", "type": "LocalPath"}], "name": "ANN Test"}', pipelines.kubeflow.org/component_ref: '{"digest":
          "8b5413d6343cfe32a9a81f3103ee02b20fa113d53dc06ac94000269ae7f1239f", "url":
          "components/neural-network/test/test.yml"}', pipelines.kubeflow.org/max_cache_staleness: P0D}
  - name: ann-train
    container:
      args: []
      command: [python, index.py, --x-train, /tmp/inputs/X_Train/data, --y-train,
        /tmp/inputs/Y_Train/data, --model, /tmp/outputs/Model/data]
      image: gcr.io/niveustraining/taxi-dataset/neural-network/train:latest
    inputs:
      artifacts:
      - {name: feature-scale-X-Train-Feature-Scaled, path: /tmp/inputs/X_Train/data}
      - {name: preprocess-Y-Train, path: /tmp/inputs/Y_Train/data}
    outputs:
      artifacts:
      - {name: ann-train-Model, path: /tmp/outputs/Model/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.10
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"command": ["python", "index.py", "--x-train", {"inputPath": "X Train"},
          "--y-train", {"inputPath": "Y Train"}, "--model", {"outputPath": "Model"}],
          "image": "gcr.io/niveustraining/taxi-dataset/neural-network/train:latest"}},
          "inputs": [{"name": "X Train", "type": "LocalPath"}, {"name": "Y Train",
          "type": "LocalPath"}], "name": "ANN Train", "outputs": [{"name": "Model",
          "type": "LocalPath"}]}', pipelines.kubeflow.org/component_ref: '{"digest":
          "43623b2d94b74c13ae84d12c03ccf975cf63b9207d4d028fe1bea881456438cb", "url":
          "components/neural-network/train/train.yml"}'}
  - name: bigquery
    container:
      args: []
      command: [python, index.py, --dataset, /tmp/outputs/Dataset/data]
      image: gcr.io/niveustraining/taxi-dataset/get-data:latest
    outputs:
      artifacts:
      - {name: bigquery-Dataset, path: /tmp/outputs/Dataset/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.10
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"command": ["python", "index.py", "--dataset", {"outputPath": "Dataset"}],
          "image": "gcr.io/niveustraining/taxi-dataset/get-data:latest"}}, "name":
          "BigQuery", "outputs": [{"name": "Dataset", "type": "LocalPath"}]}', pipelines.kubeflow.org/component_ref: '{"digest":
          "bce0d18db7db70265f162224334f484185c989450a113bad01b06cf74a3d33a7", "url":
          "components/get-data/get-data.yml"}', pipelines.kubeflow.org/max_cache_staleness: P0D}
  - name: chicago-taxi-dataset
    dag:
      tasks:
      - name: ann-test
        template: ann-test
        dependencies: [ann-train, feature-scale, preprocess]
        arguments:
          artifacts:
          - {name: ann-train-Model, from: '{{tasks.ann-train.outputs.artifacts.ann-train-Model}}'}
          - {name: feature-scale-X-Test-Feature-Scaled, from: '{{tasks.feature-scale.outputs.artifacts.feature-scale-X-Test-Feature-Scaled}}'}
          - {name: preprocess-Y-Test, from: '{{tasks.preprocess.outputs.artifacts.preprocess-Y-Test}}'}
      - name: ann-train
        template: ann-train
        dependencies: [feature-scale, preprocess]
        arguments:
          artifacts:
          - {name: feature-scale-X-Train-Feature-Scaled, from: '{{tasks.feature-scale.outputs.artifacts.feature-scale-X-Train-Feature-Scaled}}'}
          - {name: preprocess-Y-Train, from: '{{tasks.preprocess.outputs.artifacts.preprocess-Y-Train}}'}
      - {name: bigquery, template: bigquery}
      - name: feature-scale
        template: feature-scale
        dependencies: [preprocess]
        arguments:
          artifacts:
          - {name: preprocess-X-Test, from: '{{tasks.preprocess.outputs.artifacts.preprocess-X-Test}}'}
          - {name: preprocess-X-Train, from: '{{tasks.preprocess.outputs.artifacts.preprocess-X-Train}}'}
      - name: prepare-data
        template: prepare-data
        dependencies: [bigquery]
        arguments:
          artifacts:
          - {name: bigquery-Dataset, from: '{{tasks.bigquery.outputs.artifacts.bigquery-Dataset}}'}
      - name: preprocess
        template: preprocess
        dependencies: [prepare-data]
        arguments:
          artifacts:
          - {name: prepare-data-X, from: '{{tasks.prepare-data.outputs.artifacts.prepare-data-X}}'}
          - {name: prepare-data-Y, from: '{{tasks.prepare-data.outputs.artifacts.prepare-data-Y}}'}
  - name: feature-scale
    container:
      args: []
      command: [python, index.py, --x-train, /tmp/inputs/X_Train/data, --x-test, /tmp/inputs/X_Test/data,
        --X-train, /tmp/outputs/X_Train_Feature_Scaled/data, --X-test, /tmp/outputs/X_Test_Feature_Scaled/data,
        --standard-scaler, /tmp/outputs/Standard_Scaler/data]
      image: gcr.io/niveustraining/taxi-dataset/feature-scale
    inputs:
      artifacts:
      - {name: preprocess-X-Test, path: /tmp/inputs/X_Test/data}
      - {name: preprocess-X-Train, path: /tmp/inputs/X_Train/data}
    outputs:
      artifacts:
      - {name: feature-scale-Standard-Scaler, path: /tmp/outputs/Standard_Scaler/data}
      - {name: feature-scale-X-Test-Feature-Scaled, path: /tmp/outputs/X_Test_Feature_Scaled/data}
      - {name: feature-scale-X-Train-Feature-Scaled, path: /tmp/outputs/X_Train_Feature_Scaled/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.10
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"command": ["python", "index.py", "--x-train", {"inputPath": "X Train"},
          "--x-test", {"inputPath": "X Test"}, "--X-train", {"outputPath": "X Train
          Feature Scaled"}, "--X-test", {"outputPath": "X Test Feature Scaled"}, "--standard-scaler",
          {"outputPath": "Standard Scaler"}], "image": "gcr.io/niveustraining/taxi-dataset/feature-scale"}},
          "inputs": [{"name": "X Train", "type": "LocalPath"}, {"name": "X Test",
          "type": "LocalPath"}], "name": "Feature Scale", "outputs": [{"name": "X
          Train Feature Scaled", "type": "LocalPath"}, {"name": "X Test Feature Scaled",
          "type": "LocalPath"}, {"name": "Standard Scaler", "type": "LocalPath"}]}',
        pipelines.kubeflow.org/component_ref: '{"digest": "2c8570e7ce2d0177e09cea67016e1bb4c92aef751f95ed6d80bd8c40566daaed",
          "url": "components/feature-scale/feature-scale.yml"}'}
  - name: prepare-data
    container:
      args: []
      command: [python, index.py, --dataset, /tmp/inputs/Dataset/data, --X, /tmp/outputs/X/data,
        --y, /tmp/outputs/Y/data]
      image: gcr.io/niveustraining/taxi-dataset/data-preparation:latest
    inputs:
      artifacts:
      - {name: bigquery-Dataset, path: /tmp/inputs/Dataset/data}
    outputs:
      artifacts:
      - {name: prepare-data-X, path: /tmp/outputs/X/data}
      - {name: prepare-data-Y, path: /tmp/outputs/Y/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.10
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"command": ["python", "index.py", "--dataset", {"inputPath": "Dataset"},
          "--X", {"outputPath": "X"}, "--y", {"outputPath": "Y"}], "image": "gcr.io/niveustraining/taxi-dataset/data-preparation:latest"}},
          "inputs": [{"name": "Dataset", "type": "LocalPath"}], "name": "Prepare Data",
          "outputs": [{"name": "X", "type": "LocalPath"}, {"name": "Y", "type": "LocalPath"}]}',
        pipelines.kubeflow.org/component_ref: '{"digest": "f7c287359982fb8a7818153c1aeacd863892d917abdf72b7a8cefe02cec134b8",
          "url": "components/data-preparation/data-preparation.yml"}'}
  - name: preprocess
    container:
      args: []
      command: [python, index.py, --X, /tmp/inputs/X/data, --y, /tmp/inputs/Y/data,
        --x-train, /tmp/outputs/X_Train/data, --y-train, /tmp/outputs/Y_Train/data,
        --x-test, /tmp/outputs/X_Test/data, --y-test, /tmp/outputs/Y_Test/data, --column-transformer,
        /tmp/outputs/Column_Transformer/data]
      image: gcr.io/niveustraining/taxi-dataset/preprocessing:latest
    inputs:
      artifacts:
      - {name: prepare-data-X, path: /tmp/inputs/X/data}
      - {name: prepare-data-Y, path: /tmp/inputs/Y/data}
    outputs:
      artifacts:
      - {name: preprocess-Column-Transformer, path: /tmp/outputs/Column_Transformer/data}
      - {name: preprocess-X-Test, path: /tmp/outputs/X_Test/data}
      - {name: preprocess-X-Train, path: /tmp/outputs/X_Train/data}
      - {name: preprocess-Y-Test, path: /tmp/outputs/Y_Test/data}
      - {name: preprocess-Y-Train, path: /tmp/outputs/Y_Train/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.10
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"command": ["python", "index.py", "--X", {"inputPath": "X"}, "--y", {"inputPath":
          "Y"}, "--x-train", {"outputPath": "X Train"}, "--y-train", {"outputPath":
          "Y Train"}, "--x-test", {"outputPath": "X Test"}, "--y-test", {"outputPath":
          "Y Test"}, "--column-transformer", {"outputPath": "Column Transformer"}],
          "image": "gcr.io/niveustraining/taxi-dataset/preprocessing:latest"}}, "inputs":
          [{"name": "X", "type": "LocalPath"}, {"name": "Y", "type": "LocalPath"}],
          "name": "Preprocess", "outputs": [{"name": "X Train", "type": "LocalPath"},
          {"name": "Y Train", "type": "LocalPath"}, {"name": "X Test", "type": "LocalPath"},
          {"name": "Y Test", "type": "LocalPath"}, {"name": "Column Transformer",
          "type": "LocalPath"}]}', pipelines.kubeflow.org/component_ref: '{"digest":
          "95915944d1dd9c9c7a7f302a81a3cef504b2374b136fc31dcbea6f2e8931a0c0", "url":
          "components/preprocessing/preprocessing.yml"}'}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
